//! COM vtable declarations, generated from Windows metadata. Do not edit.
//!
//! Generated by tools/bindgen/gen.py from the metadata package pinned in toolchain.lock.
//! ADR-002 makes generated declarations a condition of the D3D11 backend's acceptance: seven
//! slot errors were found in the hand-written harness, every one of which compiled and
//! returned S_OK while calling the wrong method.
//!
//! metadata sha256: 64e7d92c8e08780570d5d1ce954d03f73e162f13e9b03fc5bb98f44edef26b9e
//! interfaces:      19
//! structs:         38 generated, 4 left opaque
//! opaque fallbacks: 140 parameters whose type is a struct not generated here.
//!   Each is a `?*anyopaque` with the metadata's name in a comment. They are counted rather
//!   than hidden, because an untyped parameter is a place a caller can still get it wrong.

const std = @import("std");
const GUID = std.os.windows.GUID;
const HRESULT = std.os.windows.HRESULT;

pub const IUnknownVtbl = extern struct {
    QueryInterface: *const fn (*anyopaque, *const GUID, *?*anyopaque) callconv(.winapi) HRESULT,
    AddRef: *const fn (*anyopaque) callconv(.winapi) u32,
    Release: *const fn (*anyopaque) callconv(.winapi) u32,
};

pub const D3D11_BLEND_DESC = extern struct {
    AlphaToCoverageEnable: i32,
    IndependentBlendEnable: i32,
    RenderTarget: [8]D3D11_RENDER_TARGET_BLEND_DESC,
};

pub const D3D11_BOX = extern struct {
    left: u32,
    top: u32,
    front: u32,
    right: u32,
    bottom: u32,
    back: u32,
};

pub const D3D11_BUFFER_DESC = extern struct {
    ByteWidth: u32,
    Usage: i32,
    BindFlags: u32,
    CPUAccessFlags: u32,
    MiscFlags: u32,
    StructureByteStride: u32,
};

pub const D3D11_COUNTER_DESC = extern struct {
    Counter: i32,
    MiscFlags: u32,
};

pub const D3D11_COUNTER_INFO = extern struct {
    LastDeviceDependentCounter: i32,
    NumSimultaneousCounters: u32,
    NumDetectableParallelUnits: u8,
};

pub const D3D11_DEPTH_STENCILOP_DESC = extern struct {
    StencilFailOp: i32,
    StencilDepthFailOp: i32,
    StencilPassOp: i32,
    StencilFunc: i32,
};

pub const D3D11_DEPTH_STENCIL_DESC = extern struct {
    DepthEnable: i32,
    DepthWriteMask: i32,
    DepthFunc: i32,
    StencilEnable: i32,
    StencilReadMask: u8,
    StencilWriteMask: u8,
    FrontFace: D3D11_DEPTH_STENCILOP_DESC,
    BackFace: D3D11_DEPTH_STENCILOP_DESC,
};

pub const D3D11_INFO_QUEUE_FILTER = extern struct {
    AllowList: D3D11_INFO_QUEUE_FILTER_DESC,
    DenyList: D3D11_INFO_QUEUE_FILTER_DESC,
};

pub const D3D11_INFO_QUEUE_FILTER_DESC = extern struct {
    NumCategories: u32,
    pCategoryList: ?*i32,
    NumSeverities: u32,
    pSeverityList: ?*i32,
    NumIDs: u32,
    pIDList: ?*i32,
};

pub const D3D11_INPUT_ELEMENT_DESC = extern struct {
    SemanticName: ?[*:0]u8,
    SemanticIndex: u32,
    Format: i32,
    InputSlot: u32,
    AlignedByteOffset: u32,
    InputSlotClass: i32,
    InstanceDataStepRate: u32,
};

pub const D3D11_MAPPED_SUBRESOURCE = extern struct {
    pData: ?*anyopaque,
    RowPitch: u32,
    DepthPitch: u32,
};

pub const D3D11_MESSAGE = extern struct {
    Category: i32,
    Severity: i32,
    ID: i32,
    pDescription: ?*u8,
    DescriptionByteLength: usize,
};

pub const D3D11_QUERY_DESC = extern struct {
    Query: i32,
    MiscFlags: u32,
};

pub const D3D11_RASTERIZER_DESC = extern struct {
    FillMode: i32,
    CullMode: i32,
    FrontCounterClockwise: i32,
    DepthBias: i32,
    DepthBiasClamp: f32,
    SlopeScaledDepthBias: f32,
    DepthClipEnable: i32,
    ScissorEnable: i32,
    MultisampleEnable: i32,
    AntialiasedLineEnable: i32,
};

pub const D3D11_RENDER_TARGET_BLEND_DESC = extern struct {
    BlendEnable: i32,
    SrcBlend: i32,
    DestBlend: i32,
    BlendOp: i32,
    SrcBlendAlpha: i32,
    DestBlendAlpha: i32,
    BlendOpAlpha: i32,
    RenderTargetWriteMask: u8,
};

pub const D3D11_SAMPLER_DESC = extern struct {
    Filter: i32,
    AddressU: i32,
    AddressV: i32,
    AddressW: i32,
    MipLODBias: f32,
    MaxAnisotropy: u32,
    ComparisonFunc: i32,
    BorderColor: [4]f32,
    MinLOD: f32,
    MaxLOD: f32,
};

pub const D3D11_SO_DECLARATION_ENTRY = extern struct {
    Stream: u32,
    SemanticName: ?[*:0]u8,
    SemanticIndex: u32,
    StartComponent: u8,
    ComponentCount: u8,
    OutputSlot: u8,
};

pub const D3D11_SUBRESOURCE_DATA = extern struct {
    pSysMem: ?*anyopaque,
    SysMemPitch: u32,
    SysMemSlicePitch: u32,
};

pub const D3D11_TEXTURE1D_DESC = extern struct {
    Width: u32,
    MipLevels: u32,
    ArraySize: u32,
    Format: i32,
    Usage: i32,
    BindFlags: u32,
    CPUAccessFlags: u32,
    MiscFlags: u32,
};

pub const D3D11_TEXTURE2D_DESC = extern struct {
    Width: u32,
    Height: u32,
    MipLevels: u32,
    ArraySize: u32,
    Format: i32,
    SampleDesc: DXGI_SAMPLE_DESC,
    Usage: i32,
    BindFlags: u32,
    CPUAccessFlags: u32,
    MiscFlags: u32,
};

pub const D3D11_TEXTURE3D_DESC = extern struct {
    Width: u32,
    Height: u32,
    Depth: u32,
    MipLevels: u32,
    Format: i32,
    Usage: i32,
    BindFlags: u32,
    CPUAccessFlags: u32,
    MiscFlags: u32,
};

pub const D3D11_VIEWPORT = extern struct {
    TopLeftX: f32,
    TopLeftY: f32,
    Width: f32,
    Height: f32,
    MinDepth: f32,
    MaxDepth: f32,
};

pub const DXGI_ADAPTER_DESC = extern struct {
    Description: [128]u16,
    VendorId: u32,
    DeviceId: u32,
    SubSysId: u32,
    Revision: u32,
    DedicatedVideoMemory: usize,
    DedicatedSystemMemory: usize,
    SharedSystemMemory: usize,
    AdapterLuid: LUID,
};

pub const DXGI_FRAME_STATISTICS = extern struct {
    PresentCount: u32,
    PresentRefreshCount: u32,
    SyncRefreshCount: u32,
    SyncQPCTime: i64,
    SyncGPUTime: i64,
};

pub const DXGI_MAPPED_RECT = extern struct {
    Pitch: i32,
    pBits: ?*u8,
};

pub const DXGI_MODE_DESC = extern struct {
    Width: u32,
    Height: u32,
    RefreshRate: DXGI_RATIONAL,
    Format: i32,
    ScanlineOrdering: i32,
    Scaling: i32,
};

pub const DXGI_PRESENT_PARAMETERS = extern struct {
    DirtyRectsCount: u32,
    pDirtyRects: ?*RECT,
    pScrollRect: ?*RECT,
    pScrollOffset: ?*POINT,
};

pub const DXGI_RATIONAL = extern struct {
    Numerator: u32,
    Denominator: u32,
};

pub const DXGI_RGBA = extern struct {
    r: f32,
    g: f32,
    b: f32,
    a: f32,
};

pub const DXGI_SAMPLE_DESC = extern struct {
    Count: u32,
    Quality: u32,
};

pub const DXGI_SHARED_RESOURCE = extern struct {
    Handle: ?*anyopaque,
};

pub const DXGI_SURFACE_DESC = extern struct {
    Width: u32,
    Height: u32,
    Format: i32,
    SampleDesc: DXGI_SAMPLE_DESC,
};

pub const DXGI_SWAP_CHAIN_DESC = extern struct {
    BufferDesc: DXGI_MODE_DESC,
    SampleDesc: DXGI_SAMPLE_DESC,
    BufferUsage: u32,
    BufferCount: u32,
    OutputWindow: ?*anyopaque,
    Windowed: i32,
    SwapEffect: i32,
    Flags: u32,
};

pub const DXGI_SWAP_CHAIN_DESC1 = extern struct {
    Width: u32,
    Height: u32,
    Format: i32,
    Stereo: i32,
    SampleDesc: DXGI_SAMPLE_DESC,
    BufferUsage: u32,
    BufferCount: u32,
    Scaling: i32,
    SwapEffect: i32,
    AlphaMode: i32,
    Flags: u32,
};

pub const DXGI_SWAP_CHAIN_FULLSCREEN_DESC = extern struct {
    RefreshRate: DXGI_RATIONAL,
    ScanlineOrdering: i32,
    Scaling: i32,
    Windowed: i32,
};

pub const LUID = extern struct {
    LowPart: u32,
    HighPart: i32,
};

pub const POINT = extern struct {
    x: i32,
    y: i32,
};

pub const RECT = extern struct {
    left: i32,
    top: i32,
    right: i32,
    bottom: i32,
};

/// ID3D11Device, 43 slots: IUnknown -> ID3D11Device.
pub const IID_ID3D11Device: GUID = .{ .Data1 = 0xdb6f6ddb, .Data2 = 0xac77, .Data3 = 0x4e88, .Data4 = .{ 0x82, 0x53, 0x81, 0x9d, 0xf9, 0xbb, 0xf1, 0x40 } };
pub const ID3D11DeviceVtbl = extern struct {
    base: IUnknownVtbl,
    CreateBuffer: *const fn (*anyopaque, ?*D3D11_BUFFER_DESC, ?*D3D11_SUBRESOURCE_DATA, ?*?*anyopaque) callconv(.winapi) i32,
    CreateTexture1D: *const fn (*anyopaque, ?*D3D11_TEXTURE1D_DESC, ?*D3D11_SUBRESOURCE_DATA, ?*?*anyopaque) callconv(.winapi) i32,
    CreateTexture2D: *const fn (*anyopaque, ?*D3D11_TEXTURE2D_DESC, ?*D3D11_SUBRESOURCE_DATA, ?*?*anyopaque) callconv(.winapi) i32,
    CreateTexture3D: *const fn (*anyopaque, ?*D3D11_TEXTURE3D_DESC, ?*D3D11_SUBRESOURCE_DATA, ?*?*anyopaque) callconv(.winapi) i32,
    /// opaque here: D3D11_SHADER_RESOURCE_VIEW_DESC
    CreateShaderResourceView: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    /// opaque here: D3D11_UNORDERED_ACCESS_VIEW_DESC
    CreateUnorderedAccessView: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    /// opaque here: D3D11_RENDER_TARGET_VIEW_DESC
    CreateRenderTargetView: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    /// opaque here: D3D11_DEPTH_STENCIL_VIEW_DESC
    CreateDepthStencilView: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateInputLayout: *const fn (*anyopaque, ?*D3D11_INPUT_ELEMENT_DESC, u32, ?*anyopaque, usize, ?*?*anyopaque) callconv(.winapi) i32,
    CreateVertexShader: *const fn (*anyopaque, ?*anyopaque, usize, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateGeometryShader: *const fn (*anyopaque, ?*anyopaque, usize, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateGeometryShaderWithStreamOutput: *const fn (*anyopaque, ?*anyopaque, usize, ?*D3D11_SO_DECLARATION_ENTRY, u32, ?*u32, u32, u32, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreatePixelShader: *const fn (*anyopaque, ?*anyopaque, usize, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateHullShader: *const fn (*anyopaque, ?*anyopaque, usize, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateDomainShader: *const fn (*anyopaque, ?*anyopaque, usize, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateComputeShader: *const fn (*anyopaque, ?*anyopaque, usize, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateClassLinkage: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateBlendState: *const fn (*anyopaque, ?*D3D11_BLEND_DESC, ?*?*anyopaque) callconv(.winapi) i32,
    CreateDepthStencilState: *const fn (*anyopaque, ?*D3D11_DEPTH_STENCIL_DESC, ?*?*anyopaque) callconv(.winapi) i32,
    CreateRasterizerState: *const fn (*anyopaque, ?*D3D11_RASTERIZER_DESC, ?*?*anyopaque) callconv(.winapi) i32,
    CreateSamplerState: *const fn (*anyopaque, ?*D3D11_SAMPLER_DESC, ?*?*anyopaque) callconv(.winapi) i32,
    CreateQuery: *const fn (*anyopaque, ?*D3D11_QUERY_DESC, ?*?*anyopaque) callconv(.winapi) i32,
    CreatePredicate: *const fn (*anyopaque, ?*D3D11_QUERY_DESC, ?*?*anyopaque) callconv(.winapi) i32,
    CreateCounter: *const fn (*anyopaque, ?*D3D11_COUNTER_DESC, ?*?*anyopaque) callconv(.winapi) i32,
    CreateDeferredContext: *const fn (*anyopaque, u32, ?*?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    OpenSharedResource: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CheckFormatSupport: *const fn (*anyopaque, i32, ?*u32) callconv(.winapi) i32,
    CheckMultisampleQualityLevels: *const fn (*anyopaque, i32, u32, ?*u32) callconv(.winapi) i32,
    CheckCounterInfo: *const fn (*anyopaque, ?*D3D11_COUNTER_INFO) callconv(.winapi) void,
    CheckCounter: *const fn (*anyopaque, ?*D3D11_COUNTER_DESC, ?*i32, ?*u32, ?[*:0]u8, ?*u32, ?[*:0]u8, ?*u32, ?[*:0]u8, ?*u32) callconv(.winapi) i32,
    CheckFeatureSupport: *const fn (*anyopaque, i32, ?*anyopaque, u32) callconv(.winapi) i32,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    GetFeatureLevel: *const fn (*anyopaque) callconv(.winapi) i32,
    GetCreationFlags: *const fn (*anyopaque) callconv(.winapi) u32,
    GetDeviceRemovedReason: *const fn (*anyopaque) callconv(.winapi) i32,
    GetImmediateContext: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    SetExceptionMode: *const fn (*anyopaque, u32) callconv(.winapi) i32,
    GetExceptionMode: *const fn (*anyopaque) callconv(.winapi) u32,
};

/// ID3D11DeviceContext, 115 slots: IUnknown -> ID3D11DeviceChild -> ID3D11DeviceContext.
pub const IID_ID3D11DeviceContext: GUID = .{ .Data1 = 0xc0bfa96c, .Data2 = 0xe089, .Data3 = 0x44fb, .Data4 = .{ 0x8e, 0xaf, 0x26, 0xf8, 0x79, 0x61, 0x90, 0xda } };
pub const ID3D11DeviceContextVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    VSSetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    PSSetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    PSSetShader: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque, u32) callconv(.winapi) void,
    PSSetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    VSSetShader: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque, u32) callconv(.winapi) void,
    DrawIndexed: *const fn (*anyopaque, u32, u32, i32) callconv(.winapi) void,
    Draw: *const fn (*anyopaque, u32, u32) callconv(.winapi) void,
    Map: *const fn (*anyopaque, ?*anyopaque, u32, i32, u32, ?*D3D11_MAPPED_SUBRESOURCE) callconv(.winapi) i32,
    Unmap: *const fn (*anyopaque, ?*anyopaque, u32) callconv(.winapi) void,
    PSSetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    IASetInputLayout: *const fn (*anyopaque, ?*anyopaque) callconv(.winapi) void,
    IASetVertexBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque, ?*u32, ?*u32) callconv(.winapi) void,
    IASetIndexBuffer: *const fn (*anyopaque, ?*anyopaque, i32, u32) callconv(.winapi) void,
    DrawIndexedInstanced: *const fn (*anyopaque, u32, u32, u32, i32, u32) callconv(.winapi) void,
    DrawInstanced: *const fn (*anyopaque, u32, u32, u32, u32) callconv(.winapi) void,
    GSSetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    GSSetShader: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque, u32) callconv(.winapi) void,
    IASetPrimitiveTopology: *const fn (*anyopaque, i32) callconv(.winapi) void,
    VSSetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    VSSetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    Begin: *const fn (*anyopaque, ?*anyopaque) callconv(.winapi) void,
    End: *const fn (*anyopaque, ?*anyopaque) callconv(.winapi) void,
    GetData: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque, u32, u32) callconv(.winapi) i32,
    SetPredication: *const fn (*anyopaque, ?*anyopaque, i32) callconv(.winapi) void,
    GSSetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    GSSetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    OMSetRenderTargets: *const fn (*anyopaque, u32, ?*?*anyopaque, ?*anyopaque) callconv(.winapi) void,
    OMSetRenderTargetsAndUnorderedAccessViews: *const fn (*anyopaque, u32, ?*?*anyopaque, ?*anyopaque, u32, u32, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    OMSetBlendState: *const fn (*anyopaque, ?*anyopaque, ?*f32, u32) callconv(.winapi) void,
    OMSetDepthStencilState: *const fn (*anyopaque, ?*anyopaque, u32) callconv(.winapi) void,
    SOSetTargets: *const fn (*anyopaque, u32, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    DrawAuto: *const fn (*anyopaque) callconv(.winapi) void,
    DrawIndexedInstancedIndirect: *const fn (*anyopaque, ?*anyopaque, u32) callconv(.winapi) void,
    DrawInstancedIndirect: *const fn (*anyopaque, ?*anyopaque, u32) callconv(.winapi) void,
    Dispatch: *const fn (*anyopaque, u32, u32, u32) callconv(.winapi) void,
    DispatchIndirect: *const fn (*anyopaque, ?*anyopaque, u32) callconv(.winapi) void,
    RSSetState: *const fn (*anyopaque, ?*anyopaque) callconv(.winapi) void,
    RSSetViewports: *const fn (*anyopaque, u32, ?*D3D11_VIEWPORT) callconv(.winapi) void,
    RSSetScissorRects: *const fn (*anyopaque, u32, ?*RECT) callconv(.winapi) void,
    CopySubresourceRegion: *const fn (*anyopaque, ?*anyopaque, u32, u32, u32, u32, ?*anyopaque, u32, ?*D3D11_BOX) callconv(.winapi) void,
    CopyResource: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) void,
    UpdateSubresource: *const fn (*anyopaque, ?*anyopaque, u32, ?*D3D11_BOX, ?*anyopaque, u32, u32) callconv(.winapi) void,
    CopyStructureCount: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) void,
    ClearRenderTargetView: *const fn (*anyopaque, ?*anyopaque, ?*f32) callconv(.winapi) void,
    ClearUnorderedAccessViewUint: *const fn (*anyopaque, ?*anyopaque, ?*u32) callconv(.winapi) void,
    ClearUnorderedAccessViewFloat: *const fn (*anyopaque, ?*anyopaque, ?*f32) callconv(.winapi) void,
    ClearDepthStencilView: *const fn (*anyopaque, ?*anyopaque, u32, f32, u8) callconv(.winapi) void,
    GenerateMips: *const fn (*anyopaque, ?*anyopaque) callconv(.winapi) void,
    SetResourceMinLOD: *const fn (*anyopaque, ?*anyopaque, f32) callconv(.winapi) void,
    GetResourceMinLOD: *const fn (*anyopaque, ?*anyopaque) callconv(.winapi) f32,
    ResolveSubresource: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque, u32, i32) callconv(.winapi) void,
    ExecuteCommandList: *const fn (*anyopaque, ?*anyopaque, i32) callconv(.winapi) void,
    HSSetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    HSSetShader: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque, u32) callconv(.winapi) void,
    HSSetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    HSSetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    DSSetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    DSSetShader: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque, u32) callconv(.winapi) void,
    DSSetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    DSSetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    CSSetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    CSSetUnorderedAccessViews: *const fn (*anyopaque, u32, u32, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    CSSetShader: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque, u32) callconv(.winapi) void,
    CSSetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    CSSetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    VSGetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    PSGetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    PSGetShader: *const fn (*anyopaque, ?*?*anyopaque, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    PSGetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    VSGetShader: *const fn (*anyopaque, ?*?*anyopaque, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    PSGetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    IAGetInputLayout: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    IAGetVertexBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque, ?*u32, ?*u32) callconv(.winapi) void,
    IAGetIndexBuffer: *const fn (*anyopaque, ?*?*anyopaque, ?*i32, ?*u32) callconv(.winapi) void,
    GSGetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    GSGetShader: *const fn (*anyopaque, ?*?*anyopaque, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    IAGetPrimitiveTopology: *const fn (*anyopaque, ?*i32) callconv(.winapi) void,
    VSGetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    VSGetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    GetPredication: *const fn (*anyopaque, ?*?*anyopaque, ?*i32) callconv(.winapi) void,
    GSGetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    GSGetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    OMGetRenderTargets: *const fn (*anyopaque, u32, ?*?*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    OMGetRenderTargetsAndUnorderedAccessViews: *const fn (*anyopaque, u32, ?*?*anyopaque, ?*?*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    OMGetBlendState: *const fn (*anyopaque, ?*?*anyopaque, ?*f32, ?*u32) callconv(.winapi) void,
    OMGetDepthStencilState: *const fn (*anyopaque, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    SOGetTargets: *const fn (*anyopaque, u32, ?*?*anyopaque) callconv(.winapi) void,
    RSGetState: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    RSGetViewports: *const fn (*anyopaque, ?*u32, ?*D3D11_VIEWPORT) callconv(.winapi) void,
    RSGetScissorRects: *const fn (*anyopaque, ?*u32, ?*RECT) callconv(.winapi) void,
    HSGetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    HSGetShader: *const fn (*anyopaque, ?*?*anyopaque, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    HSGetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    HSGetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    DSGetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    DSGetShader: *const fn (*anyopaque, ?*?*anyopaque, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    DSGetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    DSGetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    CSGetShaderResources: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    CSGetUnorderedAccessViews: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    CSGetShader: *const fn (*anyopaque, ?*?*anyopaque, ?*?*anyopaque, ?*u32) callconv(.winapi) void,
    CSGetSamplers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    CSGetConstantBuffers: *const fn (*anyopaque, u32, u32, ?*?*anyopaque) callconv(.winapi) void,
    ClearState: *const fn (*anyopaque) callconv(.winapi) void,
    Flush: *const fn (*anyopaque) callconv(.winapi) void,
    GetType: *const fn (*anyopaque) callconv(.winapi) i32,
    GetContextFlags: *const fn (*anyopaque) callconv(.winapi) u32,
    FinishCommandList: *const fn (*anyopaque, i32, ?*?*anyopaque) callconv(.winapi) i32,
};

/// ID3D11Buffer, 11 slots: IUnknown -> ID3D11DeviceChild -> ID3D11Resource -> ID3D11Buffer.
pub const IID_ID3D11Buffer: GUID = .{ .Data1 = 0x48570b85, .Data2 = 0xd1ee, .Data3 = 0x4fcd, .Data4 = .{ 0xa2, 0x50, 0xeb, 0x35, 0x07, 0x22, 0xb0, 0x37 } };
pub const ID3D11BufferVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    GetType: *const fn (*anyopaque, ?*i32) callconv(.winapi) void,
    SetEvictionPriority: *const fn (*anyopaque, u32) callconv(.winapi) void,
    GetEvictionPriority: *const fn (*anyopaque) callconv(.winapi) u32,
    GetDesc: *const fn (*anyopaque, ?*D3D11_BUFFER_DESC) callconv(.winapi) void,
};

/// ID3D11Texture2D, 11 slots: IUnknown -> ID3D11DeviceChild -> ID3D11Resource -> ID3D11Texture2D.
pub const IID_ID3D11Texture2D: GUID = .{ .Data1 = 0x6f15aaf2, .Data2 = 0xd208, .Data3 = 0x4e89, .Data4 = .{ 0x9a, 0xb4, 0x48, 0x95, 0x35, 0xd3, 0x4f, 0x9c } };
pub const ID3D11Texture2DVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    GetType: *const fn (*anyopaque, ?*i32) callconv(.winapi) void,
    SetEvictionPriority: *const fn (*anyopaque, u32) callconv(.winapi) void,
    GetEvictionPriority: *const fn (*anyopaque) callconv(.winapi) u32,
    GetDesc: *const fn (*anyopaque, ?*D3D11_TEXTURE2D_DESC) callconv(.winapi) void,
};

/// ID3D11RenderTargetView, 9 slots: IUnknown -> ID3D11DeviceChild -> ID3D11View -> ID3D11RenderTargetView.
pub const IID_ID3D11RenderTargetView: GUID = .{ .Data1 = 0xdfdba067, .Data2 = 0x0b8d, .Data3 = 0x4865, .Data4 = .{ 0x87, 0x5b, 0xd7, 0xb4, 0x51, 0x6c, 0xc1, 0x64 } };
pub const ID3D11RenderTargetViewVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    GetResource: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: D3D11_RENDER_TARGET_VIEW_DESC
    GetDesc: *const fn (*anyopaque, ?*anyopaque) callconv(.winapi) void,
};

/// ID3D11ShaderResourceView, 9 slots: IUnknown -> ID3D11DeviceChild -> ID3D11View -> ID3D11ShaderResourceView.
pub const IID_ID3D11ShaderResourceView: GUID = .{ .Data1 = 0xb0e06fe0, .Data2 = 0x8192, .Data3 = 0x4e1a, .Data4 = .{ 0xb1, 0xca, 0x36, 0xd7, 0x41, 0x47, 0x10, 0xb2 } };
pub const ID3D11ShaderResourceViewVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    GetResource: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: D3D11_SHADER_RESOURCE_VIEW_DESC
    GetDesc: *const fn (*anyopaque, ?*anyopaque) callconv(.winapi) void,
};

/// ID3D11InputLayout, 7 slots: IUnknown -> ID3D11DeviceChild -> ID3D11InputLayout.
pub const IID_ID3D11InputLayout: GUID = .{ .Data1 = 0xe4819ddc, .Data2 = 0x4cf0, .Data3 = 0x4025, .Data4 = .{ 0xbd, 0x26, 0x5d, 0xe8, 0x2a, 0x3e, 0x07, 0xb7 } };
pub const ID3D11InputLayoutVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
};

/// ID3D11VertexShader, 7 slots: IUnknown -> ID3D11DeviceChild -> ID3D11VertexShader.
pub const IID_ID3D11VertexShader: GUID = .{ .Data1 = 0x3b301d64, .Data2 = 0xd678, .Data3 = 0x4289, .Data4 = .{ 0x88, 0x97, 0x22, 0xf8, 0x92, 0x8b, 0x72, 0xf3 } };
pub const ID3D11VertexShaderVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
};

/// ID3D11PixelShader, 7 slots: IUnknown -> ID3D11DeviceChild -> ID3D11PixelShader.
pub const IID_ID3D11PixelShader: GUID = .{ .Data1 = 0xea82e40d, .Data2 = 0x51dc, .Data3 = 0x4f33, .Data4 = .{ 0x93, 0xd4, 0xdb, 0x7c, 0x91, 0x25, 0xae, 0x8c } };
pub const ID3D11PixelShaderVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
};

/// ID3D11SamplerState, 8 slots: IUnknown -> ID3D11DeviceChild -> ID3D11SamplerState.
pub const IID_ID3D11SamplerState: GUID = .{ .Data1 = 0xda6fea51, .Data2 = 0x564c, .Data3 = 0x4487, .Data4 = .{ 0x98, 0x10, 0xf0, 0xd0, 0xf9, 0xb4, 0xe3, 0xa5 } };
pub const ID3D11SamplerStateVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    GetDesc: *const fn (*anyopaque, ?*D3D11_SAMPLER_DESC) callconv(.winapi) void,
};

/// ID3D11BlendState, 8 slots: IUnknown -> ID3D11DeviceChild -> ID3D11BlendState.
pub const IID_ID3D11BlendState: GUID = .{ .Data1 = 0x75b68faa, .Data2 = 0x347d, .Data3 = 0x4159, .Data4 = .{ 0x8f, 0x45, 0xa0, 0x64, 0x0f, 0x01, 0xcd, 0x9a } };
pub const ID3D11BlendStateVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    GetDesc: *const fn (*anyopaque, ?*D3D11_BLEND_DESC) callconv(.winapi) void,
};

/// ID3D11RasterizerState, 8 slots: IUnknown -> ID3D11DeviceChild -> ID3D11RasterizerState.
pub const IID_ID3D11RasterizerState: GUID = .{ .Data1 = 0x9bb4ab81, .Data2 = 0xab1a, .Data3 = 0x4d8f, .Data4 = .{ 0xb5, 0x06, 0xfc, 0x04, 0x20, 0x0b, 0x6e, 0xe7 } };
pub const ID3D11RasterizerStateVtbl = extern struct {
    base: IUnknownVtbl,
    GetDevice: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) void,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    GetDesc: *const fn (*anyopaque, ?*D3D11_RASTERIZER_DESC) callconv(.winapi) void,
};

/// IDXGIFactory2, 25 slots: IUnknown -> IDXGIObject -> IDXGIFactory -> IDXGIFactory1 -> IDXGIFactory2.
pub const IID_IDXGIFactory2: GUID = .{ .Data1 = 0x50c83a1c, .Data2 = 0xe072, .Data3 = 0x4c48, .Data4 = .{ 0x87, 0xb0, 0x36, 0x30, 0xfa, 0x36, 0xa6, 0xd0 } };
pub const IDXGIFactory2Vtbl = extern struct {
    base: IUnknownVtbl,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetParent: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    EnumAdapters: *const fn (*anyopaque, u32, ?*?*anyopaque) callconv(.winapi) i32,
    MakeWindowAssociation: *const fn (*anyopaque, ?*anyopaque, u32) callconv(.winapi) i32,
    GetWindowAssociation: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateSwapChain: *const fn (*anyopaque, ?*anyopaque, ?*DXGI_SWAP_CHAIN_DESC, ?*?*anyopaque) callconv(.winapi) i32,
    CreateSoftwareAdapter: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    EnumAdapters1: *const fn (*anyopaque, u32, ?*?*anyopaque) callconv(.winapi) i32,
    IsCurrent: *const fn (*anyopaque) callconv(.winapi) i32,
    IsWindowedStereoEnabled: *const fn (*anyopaque) callconv(.winapi) i32,
    CreateSwapChainForHwnd: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque, ?*DXGI_SWAP_CHAIN_DESC1, ?*DXGI_SWAP_CHAIN_FULLSCREEN_DESC, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateSwapChainForCoreWindow: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque, ?*DXGI_SWAP_CHAIN_DESC1, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    GetSharedResourceAdapterLuid: *const fn (*anyopaque, ?*anyopaque, ?*LUID) callconv(.winapi) i32,
    RegisterStereoStatusWindow: *const fn (*anyopaque, ?*anyopaque, u32, ?*u32) callconv(.winapi) i32,
    RegisterStereoStatusEvent: *const fn (*anyopaque, ?*anyopaque, ?*u32) callconv(.winapi) i32,
    UnregisterStereoStatus: *const fn (*anyopaque, u32) callconv(.winapi) void,
    RegisterOcclusionStatusWindow: *const fn (*anyopaque, ?*anyopaque, u32, ?*u32) callconv(.winapi) i32,
    RegisterOcclusionStatusEvent: *const fn (*anyopaque, ?*anyopaque, ?*u32) callconv(.winapi) i32,
    UnregisterOcclusionStatus: *const fn (*anyopaque, u32) callconv(.winapi) void,
    CreateSwapChainForComposition: *const fn (*anyopaque, ?*anyopaque, ?*DXGI_SWAP_CHAIN_DESC1, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
};

/// IDXGISwapChain1, 29 slots: IUnknown -> IDXGIObject -> IDXGIDeviceSubObject -> IDXGISwapChain -> IDXGISwapChain1.
pub const IID_IDXGISwapChain1: GUID = .{ .Data1 = 0x790a45f7, .Data2 = 0x0d42, .Data3 = 0x4876, .Data4 = .{ 0x98, 0x3a, 0x0a, 0x55, 0xcf, 0xe6, 0xf4, 0xaa } };
pub const IDXGISwapChain1Vtbl = extern struct {
    base: IUnknownVtbl,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetParent: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetDevice: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    Present: *const fn (*anyopaque, u32, u32) callconv(.winapi) i32,
    /// opaque here: Guid
    GetBuffer: *const fn (*anyopaque, u32, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    SetFullscreenState: *const fn (*anyopaque, i32, ?*anyopaque) callconv(.winapi) i32,
    GetFullscreenState: *const fn (*anyopaque, ?*i32, ?*?*anyopaque) callconv(.winapi) i32,
    GetDesc: *const fn (*anyopaque, ?*DXGI_SWAP_CHAIN_DESC) callconv(.winapi) i32,
    ResizeBuffers: *const fn (*anyopaque, u32, u32, u32, i32, u32) callconv(.winapi) i32,
    ResizeTarget: *const fn (*anyopaque, ?*DXGI_MODE_DESC) callconv(.winapi) i32,
    GetContainingOutput: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    GetFrameStatistics: *const fn (*anyopaque, ?*DXGI_FRAME_STATISTICS) callconv(.winapi) i32,
    GetLastPresentCount: *const fn (*anyopaque, ?*u32) callconv(.winapi) i32,
    GetDesc1: *const fn (*anyopaque, ?*DXGI_SWAP_CHAIN_DESC1) callconv(.winapi) i32,
    GetFullscreenDesc: *const fn (*anyopaque, ?*DXGI_SWAP_CHAIN_FULLSCREEN_DESC) callconv(.winapi) i32,
    GetHwnd: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetCoreWindow: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    Present1: *const fn (*anyopaque, u32, u32, ?*DXGI_PRESENT_PARAMETERS) callconv(.winapi) i32,
    IsTemporaryMonoSupported: *const fn (*anyopaque) callconv(.winapi) i32,
    GetRestrictToOutput: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    SetBackgroundColor: *const fn (*anyopaque, ?*DXGI_RGBA) callconv(.winapi) i32,
    GetBackgroundColor: *const fn (*anyopaque, ?*DXGI_RGBA) callconv(.winapi) i32,
    SetRotation: *const fn (*anyopaque, i32) callconv(.winapi) i32,
    GetRotation: *const fn (*anyopaque, ?*i32) callconv(.winapi) i32,
};

/// IDXGIDevice, 12 slots: IUnknown -> IDXGIObject -> IDXGIDevice.
pub const IID_IDXGIDevice: GUID = .{ .Data1 = 0x54ec77fa, .Data2 = 0x1377, .Data3 = 0x44e6, .Data4 = .{ 0x8c, 0x32, 0x88, 0xfd, 0x5f, 0x44, 0xc8, 0x4c } };
pub const IDXGIDeviceVtbl = extern struct {
    base: IUnknownVtbl,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetParent: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    GetAdapter: *const fn (*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    CreateSurface: *const fn (*anyopaque, ?*DXGI_SURFACE_DESC, u32, u32, ?*DXGI_SHARED_RESOURCE, ?*?*anyopaque) callconv(.winapi) i32,
    QueryResourceResidency: *const fn (*anyopaque, ?*?*anyopaque, ?*i32, u32) callconv(.winapi) i32,
    SetGPUThreadPriority: *const fn (*anyopaque, i32) callconv(.winapi) i32,
    GetGPUThreadPriority: *const fn (*anyopaque, ?*i32) callconv(.winapi) i32,
};

/// IDXGIAdapter, 10 slots: IUnknown -> IDXGIObject -> IDXGIAdapter.
pub const IID_IDXGIAdapter: GUID = .{ .Data1 = 0x2411e7e1, .Data2 = 0x12ac, .Data3 = 0x4ccf, .Data4 = .{ 0xbd, 0x14, 0x97, 0x98, 0xe8, 0x53, 0x4d, 0xc0 } };
pub const IDXGIAdapterVtbl = extern struct {
    base: IUnknownVtbl,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetParent: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    EnumOutputs: *const fn (*anyopaque, u32, ?*?*anyopaque) callconv(.winapi) i32,
    GetDesc: *const fn (*anyopaque, ?*DXGI_ADAPTER_DESC) callconv(.winapi) i32,
    /// opaque here: Guid
    CheckInterfaceSupport: *const fn (*anyopaque, ?*anyopaque, ?*i64) callconv(.winapi) i32,
};

/// IDXGISurface, 11 slots: IUnknown -> IDXGIObject -> IDXGIDeviceSubObject -> IDXGISurface.
pub const IID_IDXGISurface: GUID = .{ .Data1 = 0xcafcb56c, .Data2 = 0x6ac3, .Data3 = 0x4889, .Data4 = .{ 0xbf, 0x47, 0x9e, 0x23, 0xbb, 0xd2, 0x60, 0xec } };
pub const IDXGISurfaceVtbl = extern struct {
    base: IUnknownVtbl,
    /// opaque here: Guid
    SetPrivateData: *const fn (*anyopaque, ?*anyopaque, u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    SetPrivateDataInterface: *const fn (*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetPrivateData: *const fn (*anyopaque, ?*anyopaque, ?*u32, ?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetParent: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    /// opaque here: Guid
    GetDevice: *const fn (*anyopaque, ?*anyopaque, ?*?*anyopaque) callconv(.winapi) i32,
    GetDesc: *const fn (*anyopaque, ?*DXGI_SURFACE_DESC) callconv(.winapi) i32,
    Map: *const fn (*anyopaque, ?*DXGI_MAPPED_RECT, u32) callconv(.winapi) i32,
    Unmap: *const fn (*anyopaque) callconv(.winapi) i32,
};

/// ID3DBlob, 5 slots: IUnknown -> ID3DBlob.
pub const IID_ID3DBlob: GUID = .{ .Data1 = 0x8ba5fb08, .Data2 = 0x5195, .Data3 = 0x40e2, .Data4 = .{ 0xac, 0x58, 0x0d, 0x98, 0x9c, 0x3a, 0x01, 0x02 } };
pub const ID3DBlobVtbl = extern struct {
    base: IUnknownVtbl,
    GetBufferPointer: *const fn (*anyopaque) callconv(.winapi) ?*anyopaque,
    GetBufferSize: *const fn (*anyopaque) callconv(.winapi) usize,
};

/// ID3D11InfoQueue, 38 slots: IUnknown -> ID3D11InfoQueue.
pub const IID_ID3D11InfoQueue: GUID = .{ .Data1 = 0x6543dbb6, .Data2 = 0x1b48, .Data3 = 0x42f5, .Data4 = .{ 0xab, 0x82, 0xe9, 0x7e, 0xc7, 0x43, 0x26, 0xf6 } };
pub const ID3D11InfoQueueVtbl = extern struct {
    base: IUnknownVtbl,
    SetMessageCountLimit: *const fn (*anyopaque, u64) callconv(.winapi) i32,
    ClearStoredMessages: *const fn (*anyopaque) callconv(.winapi) void,
    GetMessage: *const fn (*anyopaque, u64, ?*D3D11_MESSAGE, ?*usize) callconv(.winapi) i32,
    GetNumMessagesAllowedByStorageFilter: *const fn (*anyopaque) callconv(.winapi) u64,
    GetNumMessagesDeniedByStorageFilter: *const fn (*anyopaque) callconv(.winapi) u64,
    GetNumStoredMessages: *const fn (*anyopaque) callconv(.winapi) u64,
    GetNumStoredMessagesAllowedByRetrievalFilter: *const fn (*anyopaque) callconv(.winapi) u64,
    GetNumMessagesDiscardedByMessageCountLimit: *const fn (*anyopaque) callconv(.winapi) u64,
    GetMessageCountLimit: *const fn (*anyopaque) callconv(.winapi) u64,
    AddStorageFilterEntries: *const fn (*anyopaque, ?*D3D11_INFO_QUEUE_FILTER) callconv(.winapi) i32,
    GetStorageFilter: *const fn (*anyopaque, ?*D3D11_INFO_QUEUE_FILTER, ?*usize) callconv(.winapi) i32,
    ClearStorageFilter: *const fn (*anyopaque) callconv(.winapi) void,
    PushEmptyStorageFilter: *const fn (*anyopaque) callconv(.winapi) i32,
    PushCopyOfStorageFilter: *const fn (*anyopaque) callconv(.winapi) i32,
    PushStorageFilter: *const fn (*anyopaque, ?*D3D11_INFO_QUEUE_FILTER) callconv(.winapi) i32,
    PopStorageFilter: *const fn (*anyopaque) callconv(.winapi) void,
    GetStorageFilterStackSize: *const fn (*anyopaque) callconv(.winapi) u32,
    AddRetrievalFilterEntries: *const fn (*anyopaque, ?*D3D11_INFO_QUEUE_FILTER) callconv(.winapi) i32,
    GetRetrievalFilter: *const fn (*anyopaque, ?*D3D11_INFO_QUEUE_FILTER, ?*usize) callconv(.winapi) i32,
    ClearRetrievalFilter: *const fn (*anyopaque) callconv(.winapi) void,
    PushEmptyRetrievalFilter: *const fn (*anyopaque) callconv(.winapi) i32,
    PushCopyOfRetrievalFilter: *const fn (*anyopaque) callconv(.winapi) i32,
    PushRetrievalFilter: *const fn (*anyopaque, ?*D3D11_INFO_QUEUE_FILTER) callconv(.winapi) i32,
    PopRetrievalFilter: *const fn (*anyopaque) callconv(.winapi) void,
    GetRetrievalFilterStackSize: *const fn (*anyopaque) callconv(.winapi) u32,
    AddMessage: *const fn (*anyopaque, i32, i32, i32, ?[*:0]u8) callconv(.winapi) i32,
    AddApplicationMessage: *const fn (*anyopaque, i32, ?[*:0]u8) callconv(.winapi) i32,
    SetBreakOnCategory: *const fn (*anyopaque, i32, i32) callconv(.winapi) i32,
    SetBreakOnSeverity: *const fn (*anyopaque, i32, i32) callconv(.winapi) i32,
    SetBreakOnID: *const fn (*anyopaque, i32, i32) callconv(.winapi) i32,
    GetBreakOnCategory: *const fn (*anyopaque, i32) callconv(.winapi) i32,
    GetBreakOnSeverity: *const fn (*anyopaque, i32) callconv(.winapi) i32,
    GetBreakOnID: *const fn (*anyopaque, i32) callconv(.winapi) i32,
    SetMuteDebugOutput: *const fn (*anyopaque, i32) callconv(.winapi) void,
    GetMuteDebugOutput: *const fn (*anyopaque) callconv(.winapi) i32,
};

